version: '3.8'
services:
  postgres-medi-health:
    image: postgres:15
    container_name: medi-health-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_pass
      POSTGRES_DB: medi_health
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: